// Report Export Helpers

import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

export interface ReportData {
  id: string
  repoUrl: string
  owner: string
  repo: string
  overallScore: number
  breakdown: {
    readme: number
    structure: number
    activity: number
    maintainability: number
    bestPractices: number
  }
  metadata: {
    description: string | null
    stars: number
    forks: number
    openIssues: number
    language: string | null
    license: { name: string } | null
  }
  insights: {
    type: string
    primaryLanguage: string
    frameworks: string[]
    isMonorepo: boolean
    hasDocker: boolean
  }
  recommendations: string[]
  aiSummary?: string
  createdAt: string
}

export function generateMarkdownReport(data: ReportData): string {
  const scoreLabel = getScoreLabel(data.overallScore)
  
  return `# Repository Health Report

## ${data.owner}/${data.repo}

**Overall Score:** ${data.overallScore}/100 - ${scoreLabel}

**Repository:** ${data.repoUrl}

**Generated:** ${new Date(data.createdAt).toLocaleDateString()}

---

## Summary

${data.aiSummary || `This repository scored ${data.overallScore}/100 in our health assessment.`}

## Repository Stats

- ⭐ Stars: ${data.metadata.stars.toLocaleString()}
- 🍴 Forks: ${data.metadata.forks.toLocaleString()}
- 🐛 Open Issues: ${data.metadata.openIssues.toLocaleString()}
- 💻 Primary Language: ${data.metadata.language || 'N/A'}
- 📄 License: ${data.metadata.license?.name || 'N/A'}

## Score Breakdown

| Category | Score | Percentage |
|----------|-------|------------|
| README Quality | ${data.breakdown.readme}/20 | ${(data.breakdown.readme / 20 * 100).toFixed(0)}% |
| Project Structure | ${data.breakdown.structure}/20 | ${(data.breakdown.structure / 20 * 100).toFixed(0)}% |
| Activity | ${data.breakdown.activity}/20 | ${(data.breakdown.activity / 20 * 100).toFixed(0)}% |
| Maintainability | ${data.breakdown.maintainability}/20 | ${(data.breakdown.maintainability / 20 * 100).toFixed(0)}% |
| Best Practices | ${data.breakdown.bestPractices}/20 | ${(data.breakdown.bestPractices / 20 * 100).toFixed(0)}% |

## Project Insights

- **Type:** ${data.insights.type}
- **Primary Language:** ${data.insights.primaryLanguage}
- **Frameworks:** ${data.insights.frameworks.join(', ') || 'N/A'}
- **Monorepo:** ${data.insights.isMonorepo ? 'Yes' : 'No'}
- **Docker Support:** ${data.insights.hasDocker ? 'Yes' : 'No'}

## Recommendations

${data.recommendations.map((rec, i) => `${i + 1}. ${rec}`).join('\n')}

---

*Generated by RepoDoctor AI*
`
}

function getScoreLabel(score: number): string {
  if (score >= 90) return 'Excellent'
  if (score >= 75) return 'Good'
  if (score >= 60) return 'Fair'
  if (score >= 40) return 'Needs Work'
  return 'Poor'
}

export async function generatePDFReport(data: ReportData, elementId?: string): Promise<Blob> {
  const pdf = new jsPDF('p', 'mm', 'a4')
  const pageWidth = pdf.internal.pageSize.getWidth()
  const margin = 20
  let y = 20

  // Title
  pdf.setFontSize(24)
  pdf.setTextColor(0, 0, 0)
  pdf.text('Repository Health Report', margin, y)
  y += 15

  // Repo name
  pdf.setFontSize(18)
  pdf.text(`${data.owner}/${data.repo}`, margin, y)
  y += 10

  // Score
  pdf.setFontSize(14)
  const scoreLabel = getScoreLabel(data.overallScore)
  pdf.text(`Overall Score: ${data.overallScore}/100 - ${scoreLabel}`, margin, y)
  y += 15

  // Summary
  pdf.setFontSize(11)
  pdf.setTextColor(60, 60, 60)
  const summaryText = data.aiSummary || `This repository scored ${data.overallScore}/100 in our health assessment.`
  const splitSummary = pdf.splitTextToSize(summaryText, pageWidth - margin * 2)
  pdf.text(splitSummary, margin, y)
  y += splitSummary.length * 6 + 10

  // Stats
  pdf.setFontSize(12)
  pdf.setTextColor(0, 0, 0)
  pdf.text('Repository Stats', margin, y)
  y += 8

  pdf.setFontSize(10)
  pdf.setTextColor(60, 60, 60)
  pdf.text(`Stars: ${data.metadata.stars.toLocaleString()}`, margin, y)
  y += 6
  pdf.text(`Forks: ${data.metadata.forks.toLocaleString()}`, margin, y)
  y += 6
  pdf.text(`Open Issues: ${data.metadata.openIssues.toLocaleString()}`, margin, y)
  y += 6
  pdf.text(`Primary Language: ${data.metadata.language || 'N/A'}`, margin, y)
  y += 6
  pdf.text(`License: ${data.metadata.license?.name || 'N/A'}`, margin, y)
  y += 15

  // Score breakdown
  pdf.setFontSize(12)
  pdf.setTextColor(0, 0, 0)
  pdf.text('Score Breakdown', margin, y)
  y += 8

  pdf.setFontSize(10)
  pdf.setTextColor(60, 60, 60)
  
  const categories = [
    { name: 'README Quality', score: data.breakdown.readme },
    { name: 'Project Structure', score: data.breakdown.structure },
    { name: 'Activity', score: data.breakdown.activity },
    { name: 'Maintainability', score: data.breakdown.maintainability },
    { name: 'Best Practices', score: data.breakdown.bestPractices },
  ]

  for (const cat of categories) {
    pdf.text(`${cat.name}: ${cat.score}/20 (${(cat.score / 20 * 100).toFixed(0)}%)`, margin, y)
    y += 6
  }
  y += 10

  // Recommendations
  if (y > 250) {
    pdf.addPage()
    y = 20
  }

  pdf.setFontSize(12)
  pdf.setTextColor(0, 0, 0)
  pdf.text('Recommendations', margin, y)
  y += 8

  pdf.setFontSize(10)
  pdf.setTextColor(60, 60, 60)
  for (const rec of data.recommendations.slice(0, 6)) {
    const splitRec = pdf.splitTextToSize(`• ${rec}`, pageWidth - margin * 2)
    if (y + splitRec.length * 6 > 280) {
      pdf.addPage()
      y = 20
    }
    pdf.text(splitRec, margin, y)
    y += splitRec.length * 6 + 3
  }

  // Footer
  pdf.setFontSize(8)
  pdf.setTextColor(150, 150, 150)
  pdf.text('Generated by RepoDoctor AI', margin, 285)

  return pdf.output('blob')
}

export function downloadFile(blob: Blob, filename: string) {
  const url = window.URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  window.URL.revokeObjectURL(url)
}

export function copyToClipboard(text: string): Promise<void> {
  return navigator.clipboard.writeText(text)
}
